### ISSUE TITLE
Error converting value \"Upcoming\"

### ISSUE THREAD

**Issue by giubba88** [Vannevelj/TVDBSharp#16]
Hi,

i've made a small tool to rename my tv series episodes, and i'm having an issue when i search for some tv show (Mom, Vikings and Homeland), the other tv shows works fine.
Using this line of code:
TVDB tvdb = new TVDB(Myapi);
var searchResult = await tvdb.Search("mom"); 
i get the exception 
"Newtonsoft.Json.JsonSerializationException: Error converting value \"Upcoming\" to type 'TVDBSharp.Models.Enums.Status'. Path 'data[11].status', line 1, position 6176. ---> System.ArgumentException: Requested value 'Upcoming' was not found.\r\n   in Newton...".

Am i missing something? Do you know what is causing this problem?
(i'm using Version 3.0.0 downloaded from NuGet)
Thanks

**Comment by Vannevelj** [comment]
Hi @giubba88, thanks for bringing this to my attention. I've fixed this in https://github.com/Vannevelj/TVDBSharp/commit/0b0bd0ccea31a61ac6fe181b5e809a1a0338ecd8 and a new NuGet package is released at https://www.nuget.org/packages/TVDBSharp/3.0.1. It will become available as soon as NuGet has processed it, which should be in a few hours at most.
