### ISSUE TITLE
Show Banner and Fanart properties returning {http://thetvdb.com/banners/} only

### ISSUE THREAD

**Issue by miguedevel** [Vannevelj/TVDBSharp#17]
The Banner and Fanart properties for a Show used to return a full URL for the respective images but now it only returns {http://thetvdb.com/banners/}. I'm not sure how long ago it broke.

**Comment by Vannevelj** [comment]
See #18

**Comment by miguedevel** [comment]
This was a mistake on my part it just so happened the shows fanart were failing on don't actually have any values on thetvdb itself.
