### ISSUE TITLE
GetShow() failing with certain valid Ids

### ISSUE THREAD

**Issue by miguedevel** [Vannevelj/TVDBSharp#18]
Calling GetShow(370444) for example, which is the ID for https://thetvdb.com/series/50-states-of-fright causes an exception with the message: "The remote server returned an error: (403) Forbidden."

**Comment by Vannevelj** [comment]
Sounds like your API key has expired and you'll just need to generate a new one in the TVDB dev portal. I've verified just now that it still works for me so the API works as intended.

**Comment by miguedevel** [comment]
It works fine for me with my same key on https://api.thetvdb.com/swagger . It is with this library that it's failing.

**Comment by miguedevel** [comment]
Hopefully you're still getting notified but now with this Id I'm getting a different exception" {"Error converting value \"Weekdays\" to type 'System.Nullable`1[System.DayOfWeek]'. Path 'data.airsDayOfWeek', line 1, position 590."}
